apiVersion: v1
kind: Service
metadata:
  name: node-monitoring-service
spec:
  type: NodePort
  selector:
    app: node-monitoring-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
